### PR TITLE
Watch collection

### PR DESCRIPTION
**Pull request by iamchairs**

### CODE REVIEW

**Comment by iamchairs** [comment]
Can this be merged?

**Comment by thgreasi** [comment]
Can you undo .gitignore, I do you think that it is required by this repo?
Also it would be nice if you could also rebase/combine into a single commit.

**Comment by iamchairs** [comment]
I guess not. Updated .gitignore and squashed commits

**Comment by thgreasi** [comment]
Thanks for your effort :+1:
Nice PR!

**Pull request merged**
