### PR TITLE
using $watchCollection instead of $watch

### LINKED ISSUE #330: Infinite digest loop when using appendTo option with non-string value
Example JSBin:

http://jsbin.com/loqepiyasa/2/edit?html,js,console,output

Steps to reproduce:

* Create a table.
* Make the table head cells sortable with ui-sortable.
* Point the ng-model to an array of cell name to sort.
* In the sortable options passed to ui-sortable add  { appendTo: [any non-string. i.e. document.body] }

The problem actually goes away if you remove ng-model but obviously we'd like to use ng-model.

```
<div id="container" ng-controller="TestSortCtrl">
      <table>
        <thead>
          <tr ui-sortable="sortOptions" ng-model="numbers">
            <th ng-repeat="number in numbers">{{number}}</th>
          </tr>
        </thead>
      </table>
    </div>
```
```
.controller('TestSortCtrl', function($scope) {
  $scope.numbers = [1, 2, 3];
  $scope.sortOptions = {
    axis: 'x',
    items: 'th',
    helper: function(evt) {
      var target = angular.element(evt.target);
      var clone = target.clone();
      clone.css('top', target.position().top);
      return clone;
    },
    distance: 15,
    appendTo: document.body // remove this line and the issue goes away
  };
});
```

### PR DESCRIPTION
**Pull request by iamchairs**
Resolves #330

### CODE REVIEW

**Comment by thgreasi** [comment]
This seems fine to merge.
Please remove the change from the demo page.

Unfortunately, in my opinion, this can't be merged before v0.14.x (the next major release), since might break applications that use this directive with AngularJS v <= 1.0.

I wouldn't like to be in the situation that my app broke, just because I updated my bower packages to their latest bugfix releases.

**Comment by thgreasi** [comment]
It would also be great to have an (appropriately named) copy of [this test case](https://github.com/angular-ui/ui-sortable/blob/cf82c0bd3ad5f7a6a7146777ca40b152acd10732/test/sortable.e2e.spec.js#L419-L447), that uses `appendTo` with an `element` or a `jQuery collection`.

**Comment by iamchairs** [comment]
Will undo the `demo.html` changes and add a unit test for this.

How soon do you think a 0.14.x release will be available?

**Comment by thgreasi** [comment]
v0.14.x would probably be released along with angular js v1.4

**Comment by thgreasi** [comment]
Just created the new branch:
https://github.com/angular-ui/ui-sortable/tree/v0.14.x-dev

Please open a new PR to that instead.

**Comment by iamchairs** [comment]
Moved: https://github.com/angular-ui/ui-sortable/pull/333

**Pull request closed without merging**
