### PR TITLE
add note to include jqueryui before angularjs

### PR DESCRIPTION
**Pull request by harshil07**

### CODE REVIEW

**Comment by thgreasi** [comment]
First of all, thanks for the contribution. It's really great to have wide community participation.

I created a [pen example](http://codepen.io/anon/pen/ZYjgGd) that includes jquery-ui before angularjs and seems to work fine.
Can you include an example showcasing your use case that caused the error?

**Comment by thgreasi** [comment]
Oops typo. I meant "angularjs before jquery-ui".

**Comment by harshil07** [comment]
Not sure what the best tool is to create an example for this. I currently using requirejs for loading dependencies and also using jqueryui-amd version. If I don't have 'jqueryui' as a dependency for 'angular' in the config.js then I get the previously error mentioned in the issue.

**Comment by thgreasi** [comment]
What if you just define jquery as a dependency to angular, as shown by the
requirejs example, found in the README.md ?

Please feel free to fork that code example (or any other applicable) for
your demonstration purposes.

**Comment by harshil07** [comment]
I already have jquery as a dependency for angular. doesn't work though.

Best Regards,
Harshil

**Comment by thgreasi** [comment]
If you are able to provide a code example to show your case I will be happy
to merge this PR.
But my experience till now does not show what you are reporting.

**Comment by harshil07** [comment]
yep. will try and recreate a sample.

Best Regards,
Harshil

**Comment by thgreasi** [comment]
@harshil07 I'm closing this for now.
Feel free to reopen with a code example and then we can merge this.

**Pull request closed without merging**
