### PR TITLE
added `ui-preserve-size` option

### PR DESCRIPTION
**Pull request by dashawk**
This will add a new option to preserve the element widths when dragging.

### CODE REVIEW

**Comment by thgreasi** [comment]
Will this work if you don't define a helper option at all?

**Comment by dashawk** [comment]
> Will this work if you don't define a helper option at all?

Yes it will work.

**Comment by thgreasi** [comment]
Can you also confirm that this is also true when not using the multiselect add-on? I was just checking the code and I think that the internal helper method will not be used in that case.

**Comment by dashawk** [comment]
Yes it also works without the `multi-select` add-on. I can't create a `plunk` here in my workstation because of the our firewall.

Tested it in our own projects.

**Comment by thgreasi** [comment]
https://codepen.io/thgreasi/pen/boyzNP
But I have written some code, will check back during the weekend.
Thanks for working on this 👍

**Pull request merged**
